### ISSUE TITLE
Update solution to use .NET 8 (Latest)

### ISSUE THREAD

**Issue by YoussefWaelMohamedLotfy** [saraabdelsalam/Algoriza-Internship-2023BE35#1]
The solution currently targets .NET 6. The latest .NET has been released this past November (.NET 8). This issue is to address the necessity to upgrade to the latest version to benefit from all performance and development improvements

## Tasks

- [x] Update all project TFM to `net8.0`
- [x] Update all `Microsoft.*` and `Microsoft.Extensions.*` to version `8.0.0`
- [x] Make sure all Libraries are compatible with .NET 8

## Hints

- Understand what .NET Standard is
