### ISSUE TITLE
Refactor Domain Layer (a.k.a. Core Layer)

### ISSUE THREAD

**Issue by YoussefWaelMohamedLotfy** [saraabdelsalam/Algoriza-Internship-2023BE35#4]
For the current Domain Models, there are a lot of Attributes that are decorating properties for EF Core.

## Tasks to be done

- [x] Remove all attributes from the Domain Models
- [x] Add `DbSet`s to all Models
- [x] Create a EF Migration to acknowledge Db Schema

We will build on our new Folder Structure from now on. The old will be left for reference.

## References

- [EntityFramework Core Tutorial Site](https://www.entityframeworktutorial.net/efcore/conventions-in-ef-core.aspx)

## Dependent on

- #2 
- #3
