### ISSUE TITLE
Implement Application Logic, applying CQRS and using MediatR

### ISSUE THREAD

**Issue by YoussefWaelMohamedLotfy** [saraabdelsalam/Algoriza-Internship-2023BE35#8]
It's time to build up our Application Logic and organize our code.

## Tasks

- [ ] Get to know about Vertical Slice Architecture.
- [ ] Get to know about CQRS
- [ ] Get to know the [MediatR Library](https://github.com/jbogard/MediatR) and [FluentValidation Library](https://github.com/FluentValidation/FluentValidation.AspNetCore)
- [ ] Implement the application logic layer using what you learned from above

## References

- [My Graduation Project for ITI internship](https://github.com/YoussefWaelMohamedLotfy/BookingClone/tree/main/src/Services/BookingClone.Application), implemented using MediatR and applying CQRS

**Comment by YoussefWaelMohamedLotfy** [comment]
@saraabdelsalam One thing to note, do ***NOT*** return HTTP Result objects from your Handlers. Instead, return DTO objects.
